### ISSUE TITLE
Missing Namespace

### ISSUE THREAD

**Issue by tomh4** [TeamSirenix/odin-serializer#16]
Opening up a non-modified version in Unity throws this error : 
`Assets\Plugins\Sirenix\Odin Serializer\OdinBuildAutomation.cs(4,26): error CS0234: The type or namespace name 'Editor' does not exist in the namespace 'OdinSerializer' (are you missing an assembly reference?)`

Is this expected ?

**Comment by KyleStank** [comment]
I have the same issue. This happens on both Unity 2018.3 and Unity 2019.1.

**Comment by mcguinnessdr** [comment]
If change the platform settings on these files it seems to fix it, change the AOT and JIT to exclude editor, and the EditorOnly to exclude standalone.  This got rid of the errors and brings up the build menu, at least, not sure if the rest of it works after completing these steps.
![image](https://user-images.githubusercontent.com/2281608/56461423-0998b300-6370-11e9-941f-d8dbfb0fccef.png)

**Comment by TorVestergaard** [comment]
Any import problems with the assemblies in newer versions of Unity should now be fixed as of [this commit](https://github.com/TeamSirenix/odin-serializer/commit/d0ad4a37134b089e3023442a9fc8b47cc9619ac5).

**Comment by RohitMoni** [comment]
Hey, not sure if this is just for me, but I'm still getting this issue coming up on the latest `master` for Odin. Using Unity 2018.4.15f1, have tried 2019.3 as well. The steps by mcguinnessdr fixes it.

**Comment by Cimajor** [comment]
Hello, I have the same issue when I'm trying to build my game with Unity build 2019.3.8f1. But I don't have "Odin serializer" folder at all. I don't have any troubles to run my game, I get the error only when I'm trying to build.

**Comment by WTF-ATuan** [comment]
Hello I have same issue too but it,s only happen when I git to other

**Comment by BergesJ** [comment]
Still happening when loading via plastic scm as a new project

**Comment by frostymm** [comment]
> Had this happen, too. I deleted the whole Sirenix folder from Asset/Plugins and re-imported the package via package manager. Now it works. EDIT: It was an issue with our git LFS setup. The files were not pulled successfully and therefore the .dll's of Odin were corrupt.

I'm also running into this issue whenever we pull down my project on another machine, how did you fix the LFS setup? It seems like all of my Dlls are busted across the entire project
